### PR TITLE
correct collide functions + add needed files to be able to install the package via pip

### PR DESCRIPTION
**Pull request by yansnow78**
*correct collide functions to use centerx, centery instead of x, y. indeed x, y return the anchor point which is not what we need when anchor is not center,center

*correct circle_colliderect

*add needed files to be able to install the package via pip

### CODE REVIEW

**Comment by QuirkyCort** [comment]
Again, it looks good. Thanks!

**Comment by QuirkyCort** [comment]
Didn't give it much thought earlier, but now I'm not so sure if the collide function should use the image center or the anchor point.

I suppose the main use of changing the anchor point is when the content of the image is not centered on the center of the image. In such cases, we would set the anchor point so that the image will rotate correctly. In such a case, then it makes sense for the collide function to follow the anchor point rather than sticking to the image center.

Granted there may be other situations when the anchor point is set, but this seems the most likely. It seems that there will be more situations when using the image center will be wrong.

No rush to change back. Open for discussion.

**Comment by yansnow78** [comment]
centerx , centery is the correct value to use. you can see run the 'test/obb_obb.py' i have commited in the next pull request to verify it

**Comment by QuirkyCort** [comment]
See this image for an example. https://imgur.com/a/paETcV6

In the above image, using the image center for collision would be incorrect as the "body" of the fireball is not in the center of the image. In such cases, it is common for us to set the anchor at the center of the fireball to ensure that it rotates correctly. If we use the anchor as the center for collision, it will also collide correctly.

There are actually 3 points to consider; center of image, anchor point (used for rotation), and center of the collision body. Ideally, we would define all 3 independently, but to keep it simple, we combine two of them. Since the anchor point is set to the center of the "body" within the image, I would think it makes more sense to use the anchor point for the center of the collision body.

We could go a step further by adding a "collision.x, collision.y", and default it to the anchor point if not set, but I can't imagine many cases where the anchor point does not coincide with the center of the collision body.

**Comment by QuirkyCort** [comment]
Added a test to demonstrate the problem with using center.

**Comment by yansnow78** [comment]
Indeed, it would be better to add a parameter to say if we want to use the center of the image or the anchor as collision center for circle colision with another form or a point.

 However for obb collision with another form or point, it's definitively the center of the image that need to be used.

 For circle detection may be we could had also a ratio parameter like in pygame collide_circle_ratio https://www.kite.com/python/docs/pygame.sprite.collide_circle_ratio.

**Comment by QuirkyCort** [comment]
Just realized that obb collision uses only the image width and height (...I haven't used pgzhelper in quite a while now). If the collision box is set to the image width and height, then using centerx/centery would certainly be the way to go.

I've added the collision_width and collision_height parameters. This allows the user to set a custom collision box, and I've created an example (centerOrAnchor2.py) that demonstrates where this will be useful. obb_collideobb was modified to use anchor xy if either collision_width/height are set, else it will use center xy.

This is by no means final, and I did not modify any of the other collision functions.

For circle, I'm not sure what's the benefit of having a collision function that scales the circle by a ratio. Wouldn't it be easier to just set the appropriate radius?

**Comment by yansnow78** [comment]
regarding having a collision function that scales the circle by a ratio, it will be beter than setting the appropriate radius as the setted radius will not adapt if we change later on the Actor scale

**Pull request merged**
